# Model settings
transition: 'uniform'                          # uniform or marginal
schedule: "cosine"
model: 'graph_tf'
diffusion_steps: 500
min_time: 0.01
n_layers: 5

rate_constant: [5., 5., 1.]
corrector_entry_time: 0.1
corrector_num_steps: 10
corrector_tau_multiplier: 1.5

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

lambda_train: [1, 1, 1]


