defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : qm9
    - encoding: encoding_default


hydra:
  job:
    chdir: True
  run:
    dir: /work/log1/antoine.siraudin/ctdgg/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}

